# Generated by Django 5.2.7 on 2025-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardMain', '0002_contacts_orders_delivery_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('session_id', 'product_name')},
            },
        ),
    ]
