# Generated by Django 5.2.7 on 2025-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardMain', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
